[package]
name = "Gipfelkreuzer"
version = "1.0.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.59", features = ["derive"] }
env_logger = "0.11.9"
log = "0.4.29"
getset = "0.1.6"
serde = { version = "1.0.228", features = ["derive"] }